CREATE TABLE IF NOT EXISTS project_materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  item_name text NOT NULL,
  quantity numeric NOT NULL,
  status text NOT NULL,
  estimated_delivery date,
  actual_delivery date,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  po_number text,
  spec_id text,
  supplier_name text,
  lead_time text,
  tracking_timeline jsonb,
  expected_arrival_date timestamptz,
  vendor_id uuid
);

CREATE TABLE IF NOT EXISTS project_issues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  severity text NOT NULL,
  status text NOT NULL,
  assigned_to uuid,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  resolved_at timestamptz,
  display_id text,
  root_cause text,
  timeline_impact text,
  cost_impact text,
  resolution_plan jsonb,
  linked_milestones jsonb
);

CREATE TABLE IF NOT EXISTS change_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  cost_impact numeric,
  time_impact_days int4,
  status text NOT NULL,
  approved_by uuid,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  display_id text,
  approval_workflow jsonb
);

CREATE TABLE IF NOT EXISTS project_resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  resource_type text NOT NULL,
  name text NOT NULL,
  allocated_hours numeric,
  productivity_score int4,
  notes text,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  actual_hours numeric,
  current_assignment text
);

CREATE TABLE IF NOT EXISTS client_approvals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  document_title text NOT NULL,
  document_url text,
  status text NOT NULL,
  comments text,
  approved_by uuid,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  actioned_at timestamptz,
  display_id text,
  milestone_name text,
  final_authority jsonb,
  attached_documents jsonb,
  approval_timeline jsonb
);

CREATE TABLE IF NOT EXISTS lessons_learned (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  impact text,
  recommendation text,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  display_id text,
  title text,
  root_cause text,
  related_media jsonb
);

CREATE TABLE IF NOT EXISTS project_handovers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  package_name text NOT NULL,
  document_url text,
  warranty_expiry date,
  status text NOT NULL,
  client_signature_url text,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  display_id text,
  description text,
  key_attributes jsonb,
  package_contents jsonb,
  sign_off_status jsonb
);

CREATE TABLE IF NOT EXISTS client_meetings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  title text NOT NULL,
  meeting_date timestamptz NOT NULL,
  attendees text,
  minutes_url text,
  action_items text,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  status text,
  description text,
  key_attributes jsonb,
  attendees_list jsonb,
  agenda_minutes jsonb,
  action_items_list jsonb
);

CREATE TABLE IF NOT EXISTS client_meeting_agendas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  topic text NOT NULL,
  duration text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz,
  Policy Command NOT NULL,
  Admins have full project access ALL NOT NULL,
  Clients can view org projects SELECT NOT NULL,
  Employees can view all projects SELECT NOT NULL,
  PMs can view assigned projects SELECT NOT NULL,
  Vendors can view assigned projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Authors and Admins can update UPDATE NOT NULL,
  Employees can create updates INSERT NOT NULL,
  PMs can create updates for assigned projects INSERT NOT NULL,
  Users can view updates for visible projects SELECT NOT NULL,
  Vendors can manage own updates ALL NOT NULL,
  Policy Command NOT NULL,
  Admins can modify all profiles ALL NOT NULL,
  Admins can view all profiles SELECT NOT NULL,
  Super Admins can view all profiles for billing SELECT NOT NULL,
  Users can view own profile SELECT NOT NULL,
  Policy Command NOT NULL,
  Authors can add attachments INSERT NOT NULL,
  Users can view attachments of visible updates SELECT NOT NULL,
  Policy Command NOT NULL,
  Anyone can view tiers SELECT NOT NULL,
  Super Admins can manage tiers ALL NOT NULL,
  Policy Command NOT NULL,
  Anyone can view settings SELECT NOT NULL,
  Super Admins can manage settings ALL NOT NULL,
  Policy Command NOT NULL,
  Admins can view their orgs break glass logs SELECT NOT NULL,
  Super Admins can insert INSERT NOT NULL,
  Super admins can view break glass logs SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins can manage org vendors ALL NOT NULL,
  Vendors can view their org assignments SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins and PMs can manage project vendors ALL NOT NULL,
  Vendors can view their project assignments SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins have full access to organizations ALL NOT NULL,
  Super Admins can view organizations for billing SELECT NOT NULL,
  Users can view their organization SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins and PMs can update org timesheets UPDATE NOT NULL,
  Admins and PMs can view org timesheets SELECT NOT NULL,
  Employees can insert own timesheets INSERT NOT NULL,
  Employees can update own pending timesheets UPDATE NOT NULL,
  Employees can view own timesheets SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins/PMs can insert meeting agendas INSERT NOT NULL,
  Users can view meeting agendas SELECT NOT NULL,
  Policy Command NOT NULL,
  Users can create comments INSERT NOT NULL,
  Users can view comments of visible updates SELECT NOT NULL,
  Policy Command NOT NULL,
  Users can manage their own tokens ALL NOT NULL,
  Policy Command NOT NULL,
  Users can manage their own notifications ALL NOT NULL,
  Policy Command NOT NULL,
  Admins/PMs can update issues UPDATE NOT NULL,
  Creators and Admins can modify project_issues ALL NOT NULL,
  PMs and Admins can insert project_issues INSERT NOT NULL,
  Users can view project_issues for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Creators and Admins can modify change_requests ALL NOT NULL,
  PMs and Admins can insert change_requests INSERT NOT NULL,
  Users can view change_requests for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Creators and Admins can modify project_resources ALL NOT NULL,
  PMs and Admins can insert project_resources INSERT NOT NULL,
  Users can view project_resources for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Clients/Admins can update approvals UPDATE NOT NULL,
  Creators and Admins can modify client_approvals ALL NOT NULL,
  PMs and Admins can insert client_approvals INSERT NOT NULL,
  Users can view client_approvals for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Creators and Admins can modify project_materials ALL NOT NULL,
  PMs and Admins can insert project_materials INSERT NOT NULL,
  Users can view project_materials for visible projects SELECT NOT NULL,
  Vendors can manage assigned materials ALL NOT NULL,
  Policy Command NOT NULL,
  Creators and Admins can modify lessons_learned ALL NOT NULL,
  PMs and Admins can insert lessons_learned INSERT NOT NULL,
  Users can view lessons_learned for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins/PMs can update handover packages UPDATE NOT NULL,
  Creators and Admins can modify project_handovers ALL NOT NULL,
  PMs and Admins can insert project_handovers INSERT NOT NULL,
  Users can view project_handovers for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins/PMs can update client meetings UPDATE NOT NULL,
  Creators and Admins can modify client_meetings ALL NOT NULL,
  PMs and Admins can insert client_meetings INSERT NOT NULL,
  Users can view client_meetings for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  PMs can manage tasks ALL NOT NULL,
  Users can view tasks SELECT NOT NULL,
  Vendors can update assigned task status UPDATE NOT NULL,
  Policy Command NOT NULL,
  Admins can view audit logs SELECT NOT NULL,
  Deny all manual modifications to audit logs ALL NOT NULL,
  Policy Command NOT NULL,
  Creators and Admins can modify drawings ALL NOT NULL,
  PMs and Admins can manage drawings INSERT NOT NULL,
  Users can view drawings for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins can manage project config ALL NOT NULL,
  Users can view config for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  PMs and Admins can manage checklist items ALL NOT NULL,
  Users can view checklist items for visible milestones SELECT NOT NULL,
  Policy Command NOT NULL,
  Clients can acknowledge INSERT NOT NULL,
  Clients can update own acks UPDATE NOT NULL,
  Users can view acks of visible updates SELECT NOT NULL,
  Policy Command NOT NULL,
  Users can update own identity UPDATE NOT NULL,
  Users can view own identity SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins have full access to milestones ALL NOT NULL,
  PMs can create and modify milestones for assigned projects ALL NOT NULL,
  Users can view milestones for visible projects SELECT NOT NULL,
  Policy Command NOT NULL,
  Admins and Super Admins can update tickets UPDATE NOT NULL,
  Admins and Super Admins can view all tickets SELECT NOT NULL,
  Admins can view all tickets SELECT NOT NULL,
  Users can create their own tickets INSERT NOT NULL,
  Users can view their own tickets SELECT NOT NULL
);

CREATE TABLE IF NOT EXISTS drawing_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  drawing_name text NOT NULL,
  version_number int4 NOT NULL,
  file_url text NOT NULL,
  file_size_bytes int8,
  description text,
  status text NOT NULL,
  uploaded_by uuid,
  approved_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  drawing_id uuid
);

CREATE TABLE IF NOT EXISTS project_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  module_name text NOT NULL,
  is_enabled bool NOT NULL,
  updated_by uuid,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS milestone_checklist_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  milestone_id uuid NOT NULL,
  title text NOT NULL,
  is_complete bool NOT NULL,
  display_order int4 NOT NULL,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS duplicate_files (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  original_file_id uuid NOT NULL,
  duplicate_file_id uuid NOT NULL,
  similarity_score numeric NOT NULL,
  status text NOT NULL
);

CREATE TABLE IF NOT EXISTS virus_scan_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL,
  is_clean bool NOT NULL,
  threats_found text,
  scanned_at timestamptz
);

CREATE TABLE IF NOT EXISTS support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  priority text NOT NULL,
  user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL,
  resolution_notes text,
  updated_at timestamptz NOT NULL
);

